spring:
  application:
    name: exchange-service
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    defer-datasource-initialization: true
server:
  servlet:
    context-path: /customer-service/v1/
